### ISSUE TITLE
Puzzles about the InstanceMethodsAroundInterceptor

### ISSUE THREAD

**Issue by ethanlawrence** [wu-sheng/sky-walking#287]
The method InstanceMethodsAroundInterceptor.afterMethod()  may be replace origin return value?why do that?i think that is a risk while the interceptor's implements is poor.may cause break the origin business.don't know what i said right?

**Comment by wu-sheng** [comment]
First of all, you are right about altering the return value.

The `InstanceMethodsAroundInterceptor`  and `StaticMethodsAroundInterceptor` both have the capabilities to alter the return value, in both `before` and `after` methods.

* In **after**, override the origin return value.
* In **before**, even mean don't call the origin method.

The risk you mentioned is **true**, but this feature is needed in some plugins:
1. You can check the `JDBCDriverInterceptor#afterMethod`, need to create a `SWConnection` to replace the old one for keeping the connect-url.
1. This Kafka plugin( released in future ), the message is a byte array, which returns by a serializer. In order to keep the trace's cross-process continuation, agent must add a ContextCarrier into the byte array. So we must have the capability to change it.

Although we had took this risk into consideration, so since 3.2, we let the enhanced class implement `EnhancedInstance` interface and a dynamic field to carry extra info. By supporting this, we can avoid to alter return value in most cases, but not all of them, such as kafka plugin.

If you want to contribute or develop a new plugin, please make sure altering return value just is necessary.

And a final thing, sky-walking agent didn't ask the application developers to change their source code manually, but the changing is still be done in runtime. So risks of breaking application always exist, we must do these carefully.

**Comment by wu-sheng** [comment]
Closing this issue. If you need more explanations, please let me know.
