### ISSUE TITLE
why doesn't sky-walking support run-time agent?

### ISSUE THREAD

**Issue by zuochangan** [wu-sheng/sky-walking#320]
According [oracle document ](https://docs.oracle.com/javase/8/docs/api/java/lang/instrument/package-summary.html) which says one can start agents after vm startup. 

Also, I've checked [btrace](https://github.com/btraceio/btrace) which has implemented this.

Should we also support this?

**Comment by wu-sheng** [comment]
I am aware of `btrace` a long time ago, but have no chance to try it, yet. So I can give you some opinions just from my consideration, but not judging the **btrace** 's way.

According to oracle document, you can see that, if you wan to start up agent after JVM started, you need to  use `com.sun.tools.attach.VirtualMachine`, which is part of JDK, rather than JVM. So assuming we did agent that way, it means we required the users installed JDK on their product/test env. This isn't a good choice for me.

The second concern is, you can redefine and retransform a class from a agent, sure, but a class, which has already initialized, is impossible to change. This will trigger implicit issues about some objects are not being traced.

The **last and the most important** situation, in today Java ecosystem, **Spring framework** became more and more popular. We can say it's in dominant position, Right? In spring, some classes have been modify in runtime, most in booting stage. The class will be renamed and modified. Even generate the new classes by implementing the same interfaces. So if you load agent after the stage, **What is the purpose of using our agent?**

So, according to these three, I insist to use agent by command line argument, only support `premain` as you said.

And for more, I have cross-compare some commercial products, e.g. **AppDynamic**, **New Relic**, **OneAPM ApplicationInsight**, they did the same as I did.

Hope this can help you. @zuochangan . Happy for your asking.

**Comment by zuochangan** [comment]
@wu-sheng Thank you very much for your detailed explanation.

**Comment by cfk1996** [comment]
你好，我们现在有一种场景想要支持运行时增强，我们的项目支持线上热更新，比如最开始编译得到A.class，启动时被skywalking增强，运行的其实是A-sky.class。我们的热更新策略是基于修改过的java文件生成A1.class。然后用A1.class替换A.class,这在没有skywalking时是可以支持的，但是使用了skywalking导致内存里实际上是A-sky.class。会导致A1.class与A-sky.class差异巨大（A-sky.class增加了field和方法，或者修改了方法签名）而无法热更新。所以想到的方法是用A1.class传入jvm后再用skywalking增强下得到A1-sky.class，所以想要支持下运行时增强。
或者您能想到其他方法吗，谢谢！

**Comment by wu-sheng** [comment]
@cfk1996 We require the discussions on GitHub and Mail list must be in English.
